class IncomingMailsController < ApplicationController    
  require 'mail'
  skip_before_filter :verify_authenticity_token
  #before_filter :skipthelogin
  skip_before_filter :authenticate_user!

  def create
     require 'csv'
    message = Mail.new(params[:message])
    # if !message.new_record?
    #          render :text => "Success", :status => 201, :content_type => Mime::TEXT.to_s
    #      else
    #        render :text => message.errors.full_messages.join(', '), :status => 422, :content_type => Mime::TEXT.to_s
    #      end
   attachment = message.attachments.first
   #render :text => attachment
   file = StringIO.new(attachment.decoded)
   file.class.class_eval { attr_accessor :content_type }
   file.content_type = attachment.mime_type
   csv = CSV.parse(file.content_type, :headers => true, :col_sep => "|", :force_quotes => true, :quote_char => "~", :converters => :date, encoding: "ISO8859-1") 
       csv.each do |row|
                                        @contracts = Contract.find_or_create_by_unique3(row[0])
                                        @contracts.update_attributes( {
                                         :unique3 => row[0],
                                         :prntkey23 => row[1],
                                         :prntkey13 => row[2],
                                         :act_code => row[3],
                                         :accounting_confirmation_date => row[4],
                                         :act_form => row[5],
                                         :act_net => row[6],
                                         :agent => row[7],
                                         :act_booked => row[8],
                                         :credit_card_fee => row[9],
                                         :ceremonoy_location_name => row[10],
                                         :ceremonoy_address_line_1 => row[11],
                                         :ceremony_address_line_2 => row[12],
                                         :ceremony_location_city => row[13],
                                         :ceremony_instrumenttation => row[14],
                                         :seremonly_location_state => row[15],
                                         :ceremony_location_zip => row[16],
                                         :ceremony_start_time => row[17],
                                         :ceremony_charge => row[18],
                                         :cocktails_charge => row[19],
                                         :early_setup_charge => row[20],
                                         :early_setup_time => row[21],
                                         :contract_price => row[22],
                                         :charge_per_horn => row[23],
                                         :other_charges => row[24],
                                         :cocktail_instrumentation => row[25],
                                         :cocktail_time => row[26],
                                         :confirmation_date => row[27],
                                         :contract_sent_date => row[28],
                                         :contract_number => row[29],
                                         :contract_revision_number => row[30],
                                         :date_of_cancellation => row[31],
                                         :date_of_ceremony => row[32],
                                         :charge_per_dancer => row[33],
                                         :number_of_dancers => row[34],
                                         :giveaways => row[35],
                                         :giveaways_charge => row[36],
                                         :dj_tech_charge => row[37],
                                         :tech => row[38],
                                         :event_end_time => row[39],
                                         :number_of_horns => row[40],
                                         :type_of_light_show => row[41],
                                         :location_name => row[42].inspect,
                                         :location_address_line_1 => row[43],
                                         :location_address_line_2 => row[44],
                                         :location_city => row[45],
                                         :location_state => row[46],
                                         :location_zip => row[47],
                                         :location_phone => row[48],
                                         :non_commissionable_charges => row[49],
                                         :pick_up_amount => row[50],
                                         :explanation_opf_pickup_adjustment => row[51],
                                         :capital_music_player => row[52],
                                         :capital_music_pay => row[53],
                                         :base_price_of_act => row[54],
                                         :questionnaire_received_date => row[55],
                                         :questionnaire_sent_date => row[56],
                                         :referral_fee_amount => row[57],
                                         :referral_fee_to => row[58],
                                         :song_requests => row[59],
                                         :event_start_time => row[60],
                                         :contract_status => row[61],
                                         :tax_amount => row[62],
                                         :type_of_act => row[63],
                                         :type_of_event => row[64],
                                         :videographer_1 => row[65],
                                         :videographer_2 => row[66],
                                         :videgrapher_3 => row[67],
                                         :date_of_event => Date.strptime(row[68], "%m/%d/%Y").to_s(:db),
                                         :first_name => row[69],
                                         :last_name => row[70],
                                         :email_address => row[71],
                                         :company => row[72],
                                         :brides_names => row[73],
                                         :grooms_name => row[74],
                                         :home_phone => row[75],
                                         :work_phone => row[76],
                                         :cell_phone => row[77], 
                                         :party_planner => row[78],
                                         :act_notes => row[79].inspect,
                                         :contract_provisions => row[80].inspect,
                                         :reception_location => row[81]}) 
                                        end
end

protected

 def receive(message)
    require 'csv'
    attachment = message.attachments.first
                CSV.parse(attachment, {:headers => true, :col_sep => "|", :force_quotes => true, :quote_char => "~", :converters => :date, encoding: "ISO8859-1"}) do |row|
                                                @contracts = Contract.find_or_create_by_unique3(row[0])
                                                @contracts.update_attributes( {
                                                 :unique3 => row[0],
                                                 :prntkey23 => row[1],
                                                 :prntkey13 => row[2],
                                                 :act_code => row[3],
                                                 :accounting_confirmation_date => row[4],
                                                 :act_form => row[5],
                                                 :act_net => row[6],
                                                 :agent => row[7],
                                                 :act_booked => row[8],
                                                 :credit_card_fee => row[9],
                                                 :ceremonoy_location_name => row[10],
                                                 :ceremonoy_address_line_1 => row[11],
                                                 :ceremony_address_line_2 => row[12],
                                                 :ceremony_location_city => row[13],
                                                 :ceremony_instrumenttation => row[14],
                                                 :seremonly_location_state => row[15],
                                                 :ceremony_location_zip => row[16],
                                                 :ceremony_start_time => row[17],
                                                 :ceremony_charge => row[18],
                                                 :cocktails_charge => row[19],
                                                 :early_setup_charge => row[20],
                                                 :early_setup_time => row[21],
                                                 :contract_price => row[22],
                                                 :charge_per_horn => row[23],
                                                 :other_charges => row[24],
                                                 :cocktail_instrumentation => row[25],
                                                 :cocktail_time => row[26],
                                                 :confirmation_date => row[27],
                                                 :contract_sent_date => row[28],
                                                 :contract_number => row[29],
                                                 :contract_revision_number => row[30],
                                                 :date_of_cancellation => row[31],
                                                 :date_of_ceremony => row[32],
                                                 :charge_per_dancer => row[33],
                                                 :number_of_dancers => row[34],
                                                 :giveaways => row[35],
                                                 :giveaways_charge => row[36],
                                                 :dj_tech_charge => row[37],
                                                 :tech => row[38],
                                                 :event_end_time => row[39],
                                                 :number_of_horns => row[40],
                                                 :type_of_light_show => row[41],
                                                 :location_name => row[42].inspect,
                                                 :location_address_line_1 => row[43],
                                                 :location_address_line_2 => row[44],
                                                 :location_city => row[45],
                                                 :location_state => row[46],
                                                 :location_zip => row[47],
                                                 :location_phone => row[48],
                                                 :non_commissionable_charges => row[49],
                                                 :pick_up_amount => row[50],
                                                 :explanation_opf_pickup_adjustment => row[51],
                                                 :capital_music_player => row[52],
                                                 :capital_music_pay => row[53],
                                                 :base_price_of_act => row[54],
                                                 :questionnaire_received_date => row[55],
                                                 :questionnaire_sent_date => row[56],
                                                 :referral_fee_amount => row[57],
                                                 :referral_fee_to => row[58],
                                                 :song_requests => row[59],
                                                 :event_start_time => row[60],
                                                 :contract_status => row[61],
                                                 :tax_amount => row[62],
                                                 :type_of_act => row[63],
                                                 :type_of_event => row[64],
                                                 :videographer_1 => row[65],
                                                 :videographer_2 => row[66],
                                                 :videgrapher_3 => row[67],
                                                 :date_of_event => Date.strptime(row[68], "%m/%d/%Y").to_s(:db),
                                                 :first_name => row[69],
                                                 :last_name => row[70],
                                                 :email_address => row[71],
                                                 :company => row[72],
                                                 :brides_names => row[73],
                                                 :grooms_name => row[74],
                                                 :home_phone => row[75],
                                                 :work_phone => row[76],
                                                 :cell_phone => row[77], 
                                                 :party_planner => row[78],
                                                 :act_notes => row[79].inspect,
                                                 :contract_provisions => row[80].inspect,
                                                 :reception_location => row[81]}) 
                                                end
  end
end